name: Lint

on:
  pull_request:
    branches:
      - main

jobs:
  linting:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Yarn install
        run: yarn
      - name: Lint Reporter
        uses: wearerequired/lint-action@v2.2.0
        with:
          eslint: true
          prettier: true
      - name: Lint check
        run: yarn lint
      - name: Type check
        uses: andoshin11/typescript-error-reporter-action@v1.0.2
  testing:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Install node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Yarn install
        run: yarn
      - name: Run tests
        run: |
          yarn test --forceExit
